import Head from 'next/head'
import type { NextPage } from 'next'
import Header from '@/components/Header';
import Hero from '@/components/Hero';
import About from '@/components/About';
import Experience from '@/components/Experience';
import Skills from '@/components/Skills';

const Home: NextPage = () => {
  return (
    // snappable container
    <div
      className="
        text-white bg-[#111]
        h-screen snap-y snap-mandatory
        overflow-scroll z-0"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Hero */}
      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      {/* About */}
      <section id='about' className='snap-center' >
        <About />
      </section>

      {/* experience */}
      <section id='experience' className='snap-center'>
        <Experience />
      </section>

      {/* skills */}
      <section id='skills' className='snap-start'>
        <Skills />
      </section>

      {/* projects */}

      {/* contact me */}
    </div>
  )
}

export default Home;
